spring:
  application:
    name: fachinformatiker-lernapp
  
  profiles:
    active: dev
  
  datasource:
    url: jdbc:h2:mem:lernappdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: create-drop  # Für Development automatisch Schema erstellen
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
    show-sql: false
    open-in-view: false
  
  flyway:
    enabled: false  # Für Development deaktiviert, da wir create-drop nutzen
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 3600
  
  cache:
    type: simple
    cache-names:
      - users
      - questions
      - progress
  
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: false
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    com.fachinformatiker.lernapp: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/lernapp.log
    max-size: 10MB
    max-history: 30

app:
  jwt:
    secret: ThisIsAVeryLongSecretKeyForJWTTokenGenerationPleaseChangeInProduction
    expiration: 86400000
  cors:
    allowed-origins: http://localhost:3000,http://localhost:8080
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true