spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/lernapp}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:lernapp}
    password: ${DATABASE_PASSWORD:changeme}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  
  jpa:
    hibernate:
      ddl-auto: validate  # Flyway verwaltet das Schema in Production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false
  
  flyway:
    enabled: true  # In Production nutzen wir Flyway für Migrations
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  h2:
    console:
      enabled: false
  
  thymeleaf:
    cache: true
  
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false
  
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

server:
  port: ${SERVER_PORT:8080}
  servlet:
    session:
      cookie:
        secure: true

logging:
  level:
    root: WARN
    com.fachinformatiker.lernapp: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
  file:
    name: logs/lernapp.log
    max-size: 50MB
    max-history: 90

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://lernapp.example.com}
    allow-credentials: true