spring:
  datasource:
    url: jdbc:h2:mem:lernappdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    hikari:
      maximum-pool-size: 10
      
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
    
  h2:
    console:
      enabled: true
      path: /h2-console
      
  flyway:
    enabled: true
    baseline-on-migrate: true
    
  thymeleaf:
    cache: false
    check-template-location: false
    
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  port: 8080

logging:
  level:
    root: INFO
    com.fachinformatiker.lernapp: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
  # KEIN file-logging in dev - nur console
  
app:
  jwt:
    secret: dev-secret-key-this-is-not-secure-change-in-production
    expiration: 86400000
  cors:
    allowed-origins: "http://localhost:*,http://127.0.0.1:*"
    allow-credentials: true